name: hummingbird-child
display_name: Hummingbird Child
version: 1.0.0

author:
  name: Badr AZAOUI

description: Hummingbird Child
parent: hummingbird

meta:
  compatibility:
    from: 9.0.0
    to: ~